version: '3.8'

services:
  postgres:
    image: 'postgres:15'
    container_name: 'salt-postgres'
    environment:
      - POSTGRES_USER=salt
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=saltdb
#    volumes: (skapar en databas som består)
#      - ./data/pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always